# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Write key file
      env:
        CERTIFICATE: ${{ secrets.CERTIFICATE }}
      run: Set-Content Certificates\DeployableApp.pfx ([Convert]::FromBase64String($env:CERTIFICATE)) -AsByteStream
    - name: Restore, Build, Publish
      env:
        CERTIFICATEPASSWORD: ${{ secrets.CERTIFICATEPASSWORD }}
      run: dotnet publish -c Release --sc -bl:build.binlog
    - name: Delete key file
      if: ${{ always() }}
      run: del Certificates\DeployableApp.pfx
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Show Version
      uses: dotnet/nbgv@master
      id: nbgv
    - run: echo 'SemVer2=${{ steps.nbgv.outputs.SemVer2 }}'
    - name: Upload log files
      if: ${{ success() || failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: log
        path: '**/*.binlog'
    - name: Upload Squirrel package
      uses: actions/upload-artifact@v3
      with:
        name: squirrel package
        path: '**/Releases/**/*'
    - name: Release
      if: ${{ github.ref_name == 'main' }}
      uses: ncipollo/release-action@v1
      with:
        artifacts: "DeployableApp.Publish/bin/*/Releases/*"
        artifactErrorsFailBuild: true
        commit: ${{ github.ref_name }}
        tag: ${{ steps.nbgv.outputs.SemVer2 }}
