# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - uses: actions/cache@v3 # https://github.com/actions/cache/blob/main/examples.md#c---nuget
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Display .NET information
      run: dotnet --info
    - name: Import Code Signing Certificate
      env:
        CERTIFICATE: ${{ secrets.CERTIFICATE }}
        CERTIFICATEPASSWORD: ${{ secrets.CERTIFICATEPASSWORD }}
      run: |
        Set-Content DeployableApp.pfx ([Convert]::FromBase64String($env:CERTIFICATE)) -AsByteStream
        Import-PfxCertificate DeployableApp.pfx Cert:\CurrentUser\My -Password (ConvertTo-SecureString $env:CERTIFICATEPASSWORD -AsPlainText -Force)
        del DeployableApp.pfx
    - name: Restore, Build, Publish
      run: dotnet publish -c Release --sc -bl:build.binlog
    - name: Delete Code Signing Certificate
      if: ${{ always() }}
      run: dir -Recurse -Force Cert:\ -Include 8BEDD2041F652587AF7F26A70A6B0CC83BC8AE8F, 244E9E97D19E462B62735D2C67A7024BFC559E33 | del -Verbose
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Show Version
      uses: dotnet/nbgv@master
      id: nbgv
    - run: echo 'SemVer2=${{ steps.nbgv.outputs.SemVer2 }}'
    - name: Upload log files
      if: ${{ success() || failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: log
        path: '**/*.binlog'
    - name: Upload Squirrel package
      uses: actions/upload-artifact@v3
      with:
        name: squirrel package
        path: '**/Releases/**/*'
    - name: Release
      if: ${{ github.ref_name == 'main' }}
      uses: ncipollo/release-action@v1
      with:
        artifacts: "DeployableApp.Publish/bin/*/Releases/*"
        artifactErrorsFailBuild: true
        commit: ${{ github.ref_name }}
        tag: ${{ steps.nbgv.outputs.SemVer2 }}
